import type { SeatShareCurrency } from "./seats-currency";

export type SeatsSort = "earliest" | "cheapest" | "rated";

export type SeatsMode = "find" | "offer" | "yours";

export type SeatRide = {
  id: string;
  departTime: string;
  departPlace: string;
  arriveTime: string;
  arrivePlace: string;
  fromLat: number;
  fromLon: number;
  toLat: number;
  toLon: number;
  /** ISO offset for demo depart/arrive timestamps */
  tzOffset: string;
  routeMeta: string;
  driverInitials: string;
  driverName: string;
  driverVerified: boolean;
  rating: string;
  rideCount: string;
  vehicleLabel: string;
  vehicleBodyType: "sedan" | "suv" | "compact_hatchback" | "minivan";
  seatsTotal: number;
  seatsFree: number;
  note: string;
  /** Smallest currency unit for this market (USD cents, INR paise, etc.) */
  priceMinor: number;
  priceNote: string;
  cta: "book" | "ask";
  ctaHint: string;
};

const DEMO_IN: SeatRide[] = [
  {
    id: "arjun-mumbai-pune",
    departTime: "05:30",
    departPlace: "Mumbai Andheri East",
    arriveTime: "08:45",
    arrivePlace: "Pune Hinjawadi",
    fromLat: 19.1136,
    fromLon: 72.8697,
    toLat: 18.5912,
    toLon: 73.7389,
    tzOffset: "+05:30",
    routeMeta: "3 h 15 · via Expressway, one stop",
    driverInitials: "AM",
    driverName: "Arjun M.",
    driverVerified: true,
    rating: "4.9",
    rideCount: "31 rides · verified",
    vehicleLabel: "Honda City",
    vehicleBodyType: "sedan",
    seatsTotal: 4,
    seatsFree: 3,
    note: "Leaves on the dot. One bag each, no smoking.",
    priceMinor: 47_000,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
  {
    id: "neha-mumbai-pune",
    departTime: "06:15",
    departPlace: "Mumbai Bandra",
    arriveTime: "09:40",
    arrivePlace: "Pune Koregaon Park",
    fromLat: 19.0544,
    fromLon: 72.8407,
    toLat: 18.5362,
    toLon: 73.895,
    tzOffset: "+05:30",
    routeMeta: "3 h 25 · direct, no stops",
    driverInitials: "NS",
    driverName: "Neha S.",
    driverVerified: true,
    rating: "4.8",
    rideCount: "18 rides · verified",
    vehicleLabel: "Hyundai Creta",
    vehicleBodyType: "suv",
    seatsTotal: 4,
    seatsFree: 2,
    note: "Music OK, quiet after 8. Pickup at station only.",
    priceMinor: 52_000,
    priceNote: "per seat · fuel & tolls",
    cta: "ask",
    ctaHint: "DRIVER APPROVES",
  },
  {
    id: "rahul-mumbai-pune",
    departTime: "07:00",
    departPlace: "Mumbai Dadar",
    arriveTime: "10:20",
    arrivePlace: "Pune Kothrud",
    fromLat: 19.0178,
    fromLon: 72.8478,
    toLat: 18.5074,
    toLon: 73.8077,
    tzOffset: "+05:30",
    routeMeta: "3 h 20 · one stop · AC car",
    driverInitials: "RD",
    driverName: "Rahul D.",
    driverVerified: false,
    rating: "4.6",
    rideCount: "9 rides",
    vehicleLabel: "Maruti Swift",
    vehicleBodyType: "compact_hatchback",
    seatsTotal: 3,
    seatsFree: 1,
    note: "Early bird. Small bags in boot only.",
    priceMinor: 44_500,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
];

/** ~200 mi Midwest corridor — prices in USD cents per seat */
const DEMO_US: SeatRide[] = [
  {
    id: "james-chicago-milwaukee",
    departTime: "05:45",
    departPlace: "Chicago North Pulaski",
    arriveTime: "09:20",
    arrivePlace: "Milwaukee Downtown",
    fromLat: 41.903,
    fromLon: -87.727,
    toLat: 43.0389,
    toLon: -87.9065,
    tzOffset: "-05:00",
    routeMeta: "3 h 35 · I-94, one pickup",
    driverInitials: "JW",
    driverName: "James W.",
    driverVerified: true,
    rating: "4.9",
    rideCount: "28 rides · verified",
    vehicleLabel: "Toyota Camry",
    vehicleBodyType: "sedan",
    seatsTotal: 4,
    seatsFree: 3,
    note: "On time. One carry-on each, no smoking.",
    priceMinor: 3_200,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
  {
    id: "sarah-chicago-rockford",
    departTime: "06:30",
    departPlace: "Chicago Logan Square",
    arriveTime: "09:05",
    arrivePlace: "Rockford, IL",
    fromLat: 41.923,
    fromLon: -87.707,
    toLat: 42.2711,
    toLon: -89.094,
    tzOffset: "-05:00",
    routeMeta: "2 h 35 · direct, no stops",
    driverInitials: "SL",
    driverName: "Sarah L.",
    driverVerified: true,
    rating: "4.8",
    rideCount: "14 rides · verified",
    vehicleLabel: "Honda CR-V",
    vehicleBodyType: "suv",
    seatsTotal: 4,
    seatsFree: 2,
    note: "Podcasts welcome. Meet at curb only.",
    priceMinor: 3_800,
    priceNote: "per seat · fuel & tolls",
    cta: "ask",
    ctaHint: "DRIVER APPROVES",
  },
  {
    id: "marcus-chicago-wisconsin",
    departTime: "07:15",
    departPlace: "Chicago Irving Park",
    arriveTime: "10:50",
    arrivePlace: "Madison, WI",
    fromLat: 41.954,
    fromLon: -87.737,
    toLat: 43.0731,
    toLon: -89.4012,
    tzOffset: "-05:00",
    routeMeta: "3 h 35 · one stop · AC",
    driverInitials: "MR",
    driverName: "Marcus R.",
    driverVerified: false,
    rating: "4.7",
    rideCount: "11 rides",
    vehicleLabel: "Hyundai Elantra",
    vehicleBodyType: "sedan",
    seatsTotal: 3,
    seatsFree: 1,
    note: "Early start. Trunk space limited.",
    priceMinor: 2_850,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
];

const DEMO_CA: SeatRide[] = [
  {
    id: "emma-toronto-hamilton",
    departTime: "06:00",
    departPlace: "Toronto Liberty Village",
    arriveTime: "07:45",
    arrivePlace: "Hamilton, ON",
    fromLat: 43.637,
    fromLon: -79.419,
    toLat: 43.2557,
    toLon: -79.8711,
    tzOffset: "-04:00",
    routeMeta: "1 h 45 · QEW, one stop",
    driverInitials: "EC",
    driverName: "Emma C.",
    driverVerified: true,
    rating: "4.9",
    rideCount: "22 rides · verified",
    vehicleLabel: "Mazda3",
    vehicleBodyType: "sedan",
    seatsTotal: 4,
    seatsFree: 2,
    note: "Winter tires in season. One bag each.",
    priceMinor: 4_200,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
  {
    id: "liam-toronto-kitchener",
    departTime: "07:30",
    departPlace: "Toronto North York",
    arriveTime: "09:15",
    arrivePlace: "Kitchener, ON",
    fromLat: 43.7615,
    fromLon: -79.4111,
    toLat: 43.4516,
    toLon: -80.4925,
    tzOffset: "-04:00",
    routeMeta: "1 h 45 · direct",
    driverInitials: "LP",
    driverName: "Liam P.",
    driverVerified: true,
    rating: "4.8",
    rideCount: "16 rides · verified",
    vehicleLabel: "RAV4",
    vehicleBodyType: "suv",
    seatsTotal: 4,
    seatsFree: 3,
    note: "Quiet ride before 9 AM.",
    priceMinor: 4_800,
    priceNote: "per seat · fuel & tolls",
    cta: "ask",
    ctaHint: "DRIVER APPROVES",
  },
  {
    id: "aisha-toronto-london",
    departTime: "08:00",
    departPlace: "Toronto Scarborough",
    arriveTime: "10:30",
    arrivePlace: "London, ON",
    fromLat: 43.7764,
    fromLon: -79.2318,
    toLat: 42.9849,
    toLon: -81.2453,
    tzOffset: "-04:00",
    routeMeta: "2 h 30 · 401",
    driverInitials: "AK",
    driverName: "Aisha K.",
    driverVerified: false,
    rating: "4.6",
    rideCount: "8 rides",
    vehicleLabel: "Civic",
    vehicleBodyType: "compact_hatchback",
    seatsTotal: 3,
    seatsFree: 1,
    note: "Coffee stop optional. Cashless preferred.",
    priceMinor: 3_600,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
];

const DEMO_GB: SeatRide[] = [
  {
    id: "oliver-london-bristol",
    departTime: "06:15",
    departPlace: "London Paddington",
    arriveTime: "09:00",
    arrivePlace: "Bristol Temple Meads",
    fromLat: 51.5154,
    fromLon: -0.1755,
    toLat: 51.449,
    toLon: -2.581,
    tzOffset: "+00:00",
    routeMeta: "2 h 45 · M4, one stop",
    driverInitials: "OH",
    driverName: "Oliver H.",
    driverVerified: true,
    rating: "4.9",
    rideCount: "26 rides · verified",
    vehicleLabel: "VW Golf",
    vehicleBodyType: "compact_hatchback",
    seatsTotal: 4,
    seatsFree: 2,
    note: "Right-side pickup only. No eating in car.",
    priceMinor: 2_400,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
  {
    id: "priya-london-oxford",
    departTime: "07:00",
    departPlace: "London Marylebone",
    arriveTime: "08:35",
    arrivePlace: "Oxford City Centre",
    fromLat: 51.5225,
    fromLon: -0.163,
    toLat: 51.752,
    toLon: -1.2577,
    tzOffset: "+00:00",
    routeMeta: "1 h 35 · direct",
    driverInitials: "PS",
    driverName: "Priya S.",
    driverVerified: true,
    rating: "4.8",
    rideCount: "19 rides · verified",
    vehicleLabel: "Nissan Qashqai",
    vehicleBodyType: "suv",
    seatsTotal: 4,
    seatsFree: 3,
    note: "Student-friendly. Luggage in boot only.",
    priceMinor: 2_800,
    priceNote: "per seat · fuel & tolls",
    cta: "ask",
    ctaHint: "DRIVER APPROVES",
  },
  {
    id: "tom-london-birmingham",
    departTime: "07:45",
    departPlace: "London Euston",
    arriveTime: "10:15",
    arrivePlace: "Birmingham New St",
    fromLat: 51.5282,
    fromLon: -0.1337,
    toLat: 52.4778,
    toLon: -1.8986,
    tzOffset: "+00:00",
    routeMeta: "2 h 30 · M40",
    driverInitials: "TB",
    driverName: "Tom B.",
    driverVerified: false,
    rating: "4.7",
    rideCount: "12 rides",
    vehicleLabel: "Ford Focus",
    vehicleBodyType: "sedan",
    seatsTotal: 3,
    seatsFree: 1,
    note: "Leaves on time. Pet-free car.",
    priceMinor: 2_150,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
];

const DEMO_EUR: SeatRide[] = [
  {
    id: "lena-munich-nuremberg",
    departTime: "06:20",
    departPlace: "Munich Hauptbahnhof",
    arriveTime: "08:35",
    arrivePlace: "Nuremberg Altstadt",
    fromLat: 48.1408,
    fromLon: 11.555,
    toLat: 49.4521,
    toLon: 11.0767,
    tzOffset: "+02:00",
    routeMeta: "2 h 15 · A9, one stop",
    driverInitials: "LM",
    driverName: "Lena M.",
    driverVerified: true,
    rating: "4.9",
    rideCount: "24 rides · verified",
    vehicleLabel: "VW Passat",
    vehicleBodyType: "sedan",
    seatsTotal: 4,
    seatsFree: 3,
    note: "Pünktlich. Eine Tasche pro Person.",
    priceMinor: 2_900,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
  {
    id: "marco-munich-stuttgart",
    departTime: "07:10",
    departPlace: "Munich Sendling",
    arriveTime: "09:40",
    arrivePlace: "Stuttgart Mitte",
    fromLat: 48.122,
    fromLon: 11.543,
    toLat: 48.7758,
    toLon: 9.1829,
    tzOffset: "+02:00",
    routeMeta: "2 h 30 · direct",
    driverInitials: "MR",
    driverName: "Marco R.",
    driverVerified: true,
    rating: "4.8",
    rideCount: "17 rides · verified",
    vehicleLabel: "BMW X1",
    vehicleBodyType: "suv",
    seatsTotal: 4,
    seatsFree: 2,
    note: "Musik ok, leise nach 20 Uhr.",
    priceMinor: 3_400,
    priceNote: "per seat · fuel & tolls",
    cta: "ask",
    ctaHint: "DRIVER APPROVES",
  },
  {
    id: "sophie-munich-augsburg",
    departTime: "08:00",
    departPlace: "Munich Pasing",
    arriveTime: "09:05",
    arrivePlace: "Augsburg Zentrum",
    fromLat: 48.149,
    fromLon: 11.461,
    toLat: 48.3705,
    toLon: 10.8978,
    tzOffset: "+02:00",
    routeMeta: "1 h 05 · regional",
    driverInitials: "SB",
    driverName: "Sophie B.",
    driverVerified: false,
    rating: "4.6",
    rideCount: "10 rides",
    vehicleLabel: "Opel Corsa",
    vehicleBodyType: "compact_hatchback",
    seatsTotal: 3,
    seatsFree: 1,
    note: "Kurze Strecke, feste Abfahrt.",
    priceMinor: 2_500,
    priceNote: "per seat · fuel & tolls",
    cta: "book",
    ctaHint: "CONFIRMS AT ONCE",
  },
];

const DEMO_BY_CURRENCY: Record<SeatShareCurrency, SeatRide[]> = {
  INR: DEMO_IN,
  USD: DEMO_US,
  CAD: DEMO_CA,
  GBP: DEMO_GB,
  EUR: DEMO_EUR,
};

export function getSeatsDemoRides(currency: SeatShareCurrency): SeatRide[] {
  return DEMO_BY_CURRENCY[currency] ?? DEMO_US;
}

/** @deprecated Use getSeatsDemoRides(resolveSeatShareCurrency(...)) */
export const SEATS_DEMO_RIDES = DEMO_IN;
