import type { Place } from "./place-panel-types";

/** Acceptance case 1 — tier 0 thin row (81% of corpus). */
export const PLACE_PANEL_FIXTURE_TIER0: Place = {
  gers_id: "08f2664a1c2b3d4e5f6789012345678",
  name: "The Hidden Room",
  category: "cocktail_bar",
  category_label: "Cocktail bar",
  lat: 41.8892,
  lon: -87.6345,
  neighborhood: null,
  city_slug: "chicago",
  address: "1427 N Milwaukee Ave, Chicago",
  depth_tier: 0,
  short_description: null,
  description_source: null,
  description_url: null,
  website: null,
  instagram: null,
  hours: null,
  claimed: false,
  photos: [],
  would_return_pct: null,
  review_count: 0,
  group_tags: [],
  latest_review: null,
  bookable: false,
  next_slot: null,
  slots_tonight: null,
  updated_at: "",
};

/** Acceptance case 2 — tier 1 claimed, hours + IG, no photos. */
export const PLACE_PANEL_FIXTURE_TIER1: Place = {
  gers_id: "08f2664b2c3d4e5f67890123456789",
  name: "Lumen",
  category: "wine_bar",
  category_label: "Wine bar",
  lat: 41.8819,
  lon: -87.6278,
  neighborhood: "West Loop",
  city_slug: "chicago",
  address: "845 W Randolph St, Chicago",
  depth_tier: 1,
  short_description:
    "Natural-leaning wine bar with small plates and a back-room listening lounge.",
  description_source: "Operator",
  description_url: null,
  website: "https://lumen.example",
  instagram: "lumenwine",
  hours: { is_open: true, closes_at: "22:00", opens_at: null },
  claimed: true,
  photos: [],
  would_return_pct: null,
  review_count: 0,
  group_tags: [],
  latest_review: null,
  bookable: false,
  next_slot: null,
  slots_tonight: null,
  updated_at: "2026-09-04T12:00:00.000Z",
};

/** Acceptance case 3 — tier 2 full panel with photo grid + tags + booking. */
export const PLACE_PANEL_FIXTURE_TIER2: Place = {
  gers_id: "08f2664c3d4e5f678901234567890",
  name: "Estereo",
  category: "cocktail_bar",
  category_label: "Cocktail bar",
  lat: 41.9104,
  lon: -87.6774,
  neighborhood: "Logan Square",
  city_slug: "chicago",
  address: "1520 N Damen Ave, Chicago",
  depth_tier: 2,
  short_description:
    "Speakeasy-style cocktail bar known for classic drinks and a dark, intimate room.",
  description_source: "Wikidata",
  description_url: "https://www.wikidata.org/wiki/Q123",
  website: "https://theviolethour.com",
  instagram: "theviolethour",
  hours: { is_open: true, closes_at: "02:00", opens_at: null },
  claimed: true,
  photos: Array.from({ length: 14 }, (_, index) => ({
    id: `photo-${index + 1}`,
    key_prefix: `places/violet-hour/${index + 1}.jpg`,
    w: 1200,
    h: 800,
  })),
  would_return_pct: 84,
  review_count: 212,
  group_tags: [
    { label: "Fits 6-10", tone: "neutral" },
    { label: "Loud after 10", tone: "neutral" },
    { label: "No booking needed", tone: "neutral" },
    { label: "Splits the tab", tone: "neutral" },
    { label: "Stairs only", tone: "warn" },
  ],
  latest_review: {
    author_initials: "MR",
    author_name: "Marisol R.",
    text: "Got the whole back bar without booking, which never happens on a Friday.",
    visited_at: "2026-09-12T02:30:00.000Z",
    wait_minutes: 20,
  },
  bookable: true,
  next_slot: "2026-09-17T21:30:00.000Z",
  slots_tonight: 4,
  updated_at: "2026-09-10T08:00:00.000Z",
};

export const PLACE_PANEL_FIXTURE_DISTANCE = {
  miles: 1.2,
  driveMinutes: 9,
  fromGroupCentre: true,
} as const;
