"""add_user_fcm_token

Revision ID: 5e074dfd9e84
Revises: 9fbab2fccc1f
Create Date: 2026-04-07 13:20:41.975885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e074dfd9e84'
down_revision: Union[str, None] = '9fbab2fccc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_users_fcm_token'), 'users', ['fcm_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_fcm_token'), table_name='users')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
