"""add_event_columns_to_explore_contents

Revision ID: 8271b3940b89
Revises: 87fd68c8be25
Create Date: 2026-05-29 14:40:01.599330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8271b3940b89'
down_revision: Union[str, None] = '87fd68c8be25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explore_contents', sa.Column('event_id', sa.String(length=255), nullable=True))
    op.add_column('explore_contents', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('explore_contents', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('explore_contents', sa.Column('venue_name', sa.String(length=255), nullable=True))
    op.add_column('explore_contents', sa.Column('venue_lat', sa.Float(), nullable=True))
    op.add_column('explore_contents', sa.Column('venue_lon', sa.Float(), nullable=True))
    op.add_column('explore_contents', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('explore_contents', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('explore_contents', sa.Column('start_time', sa.String(length=100), nullable=True))
    op.add_column('explore_contents', sa.Column('price_min', sa.Float(), nullable=True))
    op.add_column('explore_contents', sa.Column('price_max', sa.Float(), nullable=True))
    op.add_column('explore_contents', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('explore_contents', sa.Column('ticket_url', sa.Text(), nullable=True))
    op.add_column('explore_contents', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_explore_contents_event_id'), 'explore_contents', ['event_id'], unique=True)
    op.create_index(op.f('ix_explore_contents_start_date'), 'explore_contents', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explore_contents_start_date'), table_name='explore_contents')
    op.drop_index(op.f('ix_explore_contents_event_id'), table_name='explore_contents')
    op.drop_column('explore_contents', 'source')
    op.drop_column('explore_contents', 'ticket_url')
    op.drop_column('explore_contents', 'image_url')
    op.drop_column('explore_contents', 'price_max')
    op.drop_column('explore_contents', 'price_min')
    op.drop_column('explore_contents', 'start_time')
    op.drop_column('explore_contents', 'start_date')
    op.drop_column('explore_contents', 'state')
    op.drop_column('explore_contents', 'venue_lon')
    op.drop_column('explore_contents', 'venue_lat')
    op.drop_column('explore_contents', 'venue_name')
    op.drop_column('explore_contents', 'category')
    op.drop_column('explore_contents', 'title')
    op.drop_column('explore_contents', 'event_id')
    # ### end Alembic commands ###
