"""add_email_verification_to_users

Revision ID: 1d41f034fa67
Revises: buddy_trips_20260513
Create Date: 2026-05-14 03:36:51.661320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d41f034fa67'
down_revision: Union[str, None] = 'buddy_trips_20260513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_shorts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('reaction_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_shorts_city'), 'imported_shorts', ['city'], unique=False)
    op.create_index(op.f('ix_imported_shorts_external_id'), 'imported_shorts', ['external_id'], unique=False)
    op.create_index(op.f('ix_imported_shorts_source'), 'imported_shorts', ['source'], unique=False)
    op.create_table('saved_pins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('flag_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_pins_user_id'), 'saved_pins', ['user_id'], unique=False)
    op.alter_column('buddy_requests', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_trips', 'max_size',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_trips', 'current_size',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_trips', 'vibe_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=80)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_trips', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('buddy_trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('explorer_cache', 'cache_scope',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_explorer_cache_scope_key', 'explorer_cache', type_='unique')
    op.alter_column('live_checklists', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('live_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('live_sessions', 'meet_radius_meters',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('location_hashtags', 'hashtags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('location_hashtags', 'youtube_channel_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('location_hashtags', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('location_hashtags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_token_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'deal_price_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'deal_alerts_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('users', 'deal_alerts_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'deal_price_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('300.0'),
               existing_nullable=True)
    op.drop_column('users', 'verification_token_sent_at')
    op.drop_column('users', 'verified_at')
    op.alter_column('location_hashtags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('location_hashtags', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'city'::character varying"),
               existing_nullable=False)
    op.alter_column('location_hashtags', 'youtube_channel_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('location_hashtags', 'hashtags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('live_sessions', 'meet_radius_meters',
               existing_type=sa.INTEGER(),
               server_default=sa.text('200'),
               existing_nullable=False)
    op.alter_column('live_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pre_live'::character varying"),
               existing_nullable=False)
    op.alter_column('live_checklists', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_unique_constraint('uq_explorer_cache_scope_key', 'explorer_cache', ['country_code', 'city_slug', 'module', 'radius_bucket', 'geo_bucket', 'cache_scope'])
    op.alter_column('explorer_cache', 'cache_scope',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'explorer'::character varying"),
               existing_nullable=False)
    op.alter_column('buddy_trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('buddy_trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('buddy_trips', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('buddy_trips', 'vibe_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=80)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('buddy_trips', 'current_size',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('buddy_trips', 'max_size',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('buddy_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('buddy_requests', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_saved_pins_user_id'), table_name='saved_pins')
    op.drop_table('saved_pins')
    op.drop_index(op.f('ix_imported_shorts_source'), table_name='imported_shorts')
    op.drop_index(op.f('ix_imported_shorts_external_id'), table_name='imported_shorts')
    op.drop_index(op.f('ix_imported_shorts_city'), table_name='imported_shorts')
    op.drop_table('imported_shorts')
    # ### end Alembic commands ###
