"""add location_shares table

Revision ID: 296b9d14dc3c
Revises: 2f7c9d4e3eca
Create Date: 2026-04-07 12:09:42.590816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296b9d14dc3c'
down_revision: Union[str, None] = '2f7c9d4e3eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_shares_trip_id'), 'location_shares', ['trip_id'], unique=False)
    op.create_index(op.f('ix_location_shares_user_id'), 'location_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_shares_user_id'), table_name='location_shares')
    op.drop_index(op.f('ix_location_shares_trip_id'), table_name='location_shares')
    op.drop_table('location_shares')
    # ### end Alembic commands ###
