"""add stripe fields to subscriptions

Revision ID: 2938576d8e39
Revises: f5debd2c3de8
Create Date: 2026-04-08 04:05:35.557403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2938576d8e39'
down_revision: Union[str, None] = 'f5debd2c3de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###
