"""add_meet_points_and_attendance

Revision ID: 9fbab2fccc1f
Revises: 1d6c71c5a653
Create Date: 2026-04-07 13:08:59.119586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbab2fccc1f'
down_revision: Union[str, None] = '1d6c71c5a653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meet_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('proposed_by', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('meet_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meet_points_trip_id'), 'meet_points', ['trip_id'], unique=False)
    op.create_table('meet_point_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meet_point_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meet_point_id'], ['meet_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meet_point_attendance_meet_point_id'), 'meet_point_attendance', ['meet_point_id'], unique=False)
    op.create_index(op.f('ix_meet_point_attendance_user_id'), 'meet_point_attendance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meet_point_attendance_user_id'), table_name='meet_point_attendance')
    op.drop_index(op.f('ix_meet_point_attendance_meet_point_id'), table_name='meet_point_attendance')
    op.drop_table('meet_point_attendance')
    op.drop_index(op.f('ix_meet_points_trip_id'), table_name='meet_points')
    op.drop_table('meet_points')
    # ### end Alembic commands ###
