"""add_splitwise_features

Revision ID: d1babae7a0e8
Revises: 57b8c4ea54d0
Create Date: 2026-04-28 12:38:22.805663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1babae7a0e8'
down_revision: Union[str, None] = '57b8c4ea54d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', name='uq_currency_rates_from_to')
    )
    op.create_index('ix_currency_rates_from_to', 'currency_rates', ['from_currency', 'to_currency'], unique=False)
    op.drop_index('ix_saved_pins_user_id', table_name='saved_pins')
    op.drop_table('saved_pins')
    op.add_column('expense_splits', sa.Column('share_units', sa.Float(), nullable=True))
    op.add_column('expense_splits', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('expense_splits', sa.Column('exact_amount', sa.Float(), nullable=True))
    op.add_column('expense_splits', sa.Column('notes', sa.String(length=200), nullable=True))
    op.add_column('expenses', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('expenses', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('expenses', sa.Column('receipt_url', sa.String(length=500), nullable=True))
    op.add_column('expenses', sa.Column('split_type', sa.String(length=20), server_default=sa.text("'equal'"), nullable=False))
    op.add_column('expenses', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('expenses', sa.Column('original_amount', sa.Float(), nullable=True))
    op.alter_column('expenses', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'"),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('groups', sa.Column('default_currency', sa.String(length=10), server_default=sa.text("'INR'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'default_currency')
    op.alter_column('expenses', 'currency',
               existing_type=sa.String(length=10),
               server_default=None,
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_column('expenses', 'original_amount')
    op.drop_column('expenses', 'exchange_rate')
    op.drop_column('expenses', 'split_type')
    op.drop_column('expenses', 'receipt_url')
    op.drop_column('expenses', 'notes')
    op.drop_column('expenses', 'category')
    op.drop_column('expense_splits', 'notes')
    op.drop_column('expense_splits', 'exact_amount')
    op.drop_column('expense_splits', 'percentage')
    op.drop_column('expense_splits', 'share_units')
    op.create_table('saved_pins',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('flag_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_pins_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='saved_pins_pkey')
    )
    op.create_index('ix_saved_pins_user_id', 'saved_pins', ['user_id'], unique=False)
    op.drop_index('ix_currency_rates_from_to', table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
