"""Add explore_events table

Revision ID: a4a708e5a5bf
Revises: e3f4a5b6c7d8
Create Date: 2026-05-05 14:23:11.431182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4a708e5a5bf'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explore_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price_from', sa.Float(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explore_events_city'), 'explore_events', ['city'], unique=False)
    op.create_index(op.f('ix_explore_events_external_id'), 'explore_events', ['external_id'], unique=True)
    op.create_index(op.f('ix_explore_events_start_time'), 'explore_events', ['start_time'], unique=False)
    op.alter_column('user_app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_column('users', 'avatar_animation_url')
    op.drop_column('users', 'travel_personality')
    op.drop_column('users', 'pose_id')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'ghost_mode')
    op.drop_column('users', 'avatar_config')
    op.drop_column('users', 'location')
    op.drop_column('users', 'tier')
    op.drop_column('users', 'globe_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('globe_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tier', sa.VARCHAR(length=50), server_default=sa.text("'Beginner'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ghost_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pose_id', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('travel_personality', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_animation_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('user_app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_explore_events_start_time'), table_name='explore_events')
    op.drop_index(op.f('ix_explore_events_external_id'), table_name='explore_events')
    op.drop_index(op.f('ix_explore_events_city'), table_name='explore_events')
    op.drop_table('explore_events')
    # ### end Alembic commands ###
