import type { CollectionItem } from "./collection-types";

/** Design-reference demo saves — shown when the user has no server-side items yet. */
export const COLLECTION_DEMO_UNSORTED = 6;

export const COLLECTION_SHARED_SECTIONS: Record<
  string,
  { extra: string; meta: string }
> = {
  Chicago: { extra: "+4", meta: "Shared with the Saturday group" },
  Food: { extra: "+2", meta: "Shared with the Saturday group" },
};

export const COLLECTION_CITY_ORDER = [
  "Chicago",
  "New Orleans",
  "Austin",
  "Lisbon",
] as const;

const DEMO_NOW = "2026-06-01T12:00:00.000Z";

export const COLLECTION_DEMO_ITEMS: CollectionItem[] = [
  {
    id: "demo-green",
    user_id: "demo",
    collection_id: null,
    name: "The Green Mill",
    latitude: 41.969,
    longitude: -87.66,
    city: "Chicago",
    country: "USA",
    category: "Live music",
    subcategory: "Jazz club",
    source: "Reel",
    saved_from: "Instagram reel — @chicagonights",
    note: "Ana says get there before the second set fills.",
    stars: 5,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-fulton",
    user_id: "demo",
    collection_id: null,
    name: "Fulton Kitchen",
    latitude: 41.89,
    longitude: -87.64,
    city: "Chicago",
    country: "USA",
    category: "Food",
    subcategory: "Restaurant",
    source: "Search",
    saved_from: "Searched from the map",
    note: "Long table takes eight. Deposit splits in app.",
    stars: 4,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-estereo",
    user_id: "demo",
    collection_id: null,
    name: "Estereo",
    latitude: 41.91,
    longitude: -87.67,
    city: "Chicago",
    country: "USA",
    category: "Bars",
    subcategory: "Cocktail bar",
    source: "Friend",
    saved_from: "Tomas shared it",
    note: null,
    stars: 0,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-606",
    user_id: "demo",
    collection_id: null,
    name: "606 Trail",
    latitude: 41.91,
    longitude: -87.68,
    city: "Chicago",
    country: "USA",
    category: "Outdoors",
    subcategory: "Trail",
    source: "Pin",
    saved_from: "Dropped a pin",
    note: "Runs the whole stretch, no crossings.",
    stars: 5,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-maple",
    user_id: "demo",
    collection_id: null,
    name: "Maple Leaf Bar",
    latitude: 29.94,
    longitude: -90.1,
    city: "New Orleans",
    country: "USA",
    category: "Live music",
    subcategory: "Music venue",
    source: "Reel",
    saved_from: "TikTok — @nolaafterdark",
    note: "Rebirth Brass on Tuesdays. Cash only.",
    stars: 5,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-cochon",
    user_id: "demo",
    collection_id: null,
    name: "Cochon Butcher",
    latitude: 29.94,
    longitude: -90.07,
    city: "New Orleans",
    country: "USA",
    category: "Food",
    subcategory: "Deli",
    source: "Wayra",
    saved_from: "Wayra suggested it",
    note: null,
    stars: 0,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-franklin",
    user_id: "demo",
    collection_id: null,
    name: "Franklin Barbecue",
    latitude: 30.27,
    longitude: -97.73,
    city: "Austin",
    country: "USA",
    category: "Food",
    subcategory: "Barbecue",
    source: "Reel",
    saved_from: "YouTube — Texas BBQ tour",
    note: "Queue by 9am or don't bother.",
    stars: 4,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-barton",
    user_id: "demo",
    collection_id: null,
    name: "Barton Springs",
    latitude: 30.26,
    longitude: -97.77,
    city: "Austin",
    country: "USA",
    category: "Outdoors",
    subcategory: "Swimming",
    source: "Pin",
    saved_from: "Dropped a pin",
    note: null,
    stars: 0,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-pensao",
    user_id: "demo",
    collection_id: null,
    name: "Pensão Amor",
    latitude: 38.71,
    longitude: -9.14,
    city: "Lisbon",
    country: "Portugal",
    category: "Bars",
    subcategory: "Cocktail bar",
    source: "Reel",
    saved_from: "Instagram reel — @lisboasecreta",
    note: "Upstairs is quieter than it looks.",
    stars: 4,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
  {
    id: "demo-timeout",
    user_id: "demo",
    collection_id: null,
    name: "Time Out Market",
    latitude: 38.71,
    longitude: -9.15,
    city: "Lisbon",
    country: "Portugal",
    category: "Food",
    subcategory: "Food hall",
    source: "Search",
    saved_from: "Searched from the map",
    note: null,
    stars: 0,
    match_status: "sure",
    is_unsorted: false,
    created_at: DEMO_NOW,
    updated_at: DEMO_NOW,
  },
];

/** Short card meta lines from the design comp. */
export const COLLECTION_DEMO_META: Record<string, string> = {
  "demo-green": "Live music · 3.4 mi",
  "demo-fulton": "Food · 2.6 mi",
  "demo-estereo": "Bars · 0.5 mi",
  "demo-606": "Outdoors · 0.6 mi",
  "demo-maple": "Live music · Uptown",
  "demo-cochon": "Food · Warehouse",
  "demo-franklin": "Food · East Austin",
  "demo-barton": "Outdoors · Zilker",
  "demo-pensao": "Bars · Cais do Sodré",
  "demo-timeout": "Food · Cais do Sodré",
};

export const COLLECTION_DEMO_RATING: Record<string, string> = {
  "demo-green": "4.8 ★ 4.1k",
  "demo-fulton": "4.7 ★ 1.2k",
  "demo-estereo": "4.6 ★ 1.1k",
  "demo-606": "4.8 ★ 2.7k",
  "demo-maple": "4.7 ★ 2.2k",
  "demo-cochon": "4.6 ★ 3.8k",
  "demo-franklin": "4.8 ★ 12k",
  "demo-barton": "4.7 ★ 8.4k",
  "demo-pensao": "4.4 ★ 2.9k",
  "demo-timeout": "4.3 ★ 24k",
};

export const COLLECTION_DEMO_HOURS: Record<string, string> = {
  "demo-green": "sets 9 & 11",
  "demo-fulton": "5–11 PM",
  "demo-estereo": "till 2 AM",
  "demo-606": "open till dusk",
  "demo-maple": "doors 9",
  "demo-cochon": "till 10",
  "demo-franklin": "till sold out",
  "demo-barton": "5 AM – 10 PM",
  "demo-pensao": "till 3 AM",
  "demo-timeout": "10 AM – midnight",
};
